### ISSUE TITLE
Code release 

### ISSUE THREAD

**Issue by abhigoku10** [yichen928/GEAL_active_learning#2]
@yichen928  hi thanks for the wonderful paper can you pls share the source code for this it would be very helpful 
thanks in adavnce

**Comment by yichen928** [comment]
Hi, thank you very much for your interest. After discussion with co-authors, we will release the code before the decision of this paper. I am checking and reviewing the code now. I believe you can see it in Feb.

**Comment by abhigoku10** [comment]
@yichen928  thanks for the response eagerly waiting for Feb

**Comment by tfriedel** [comment]
looking forward!

**Comment by yichen928** [comment]
> looking forward!

The code for object detection task is released now! The authors are occupied by preparing ECCV submissions now. We will release other parts after the deadline.

**Comment by tfriedel** [comment]
well that was fast! Going to have a look... thanks!

**Comment by tfriedel** [comment]
I noticed that kmeans-pytorch from pypi is not the version you used, because it doesn't support the iter_limit flag. I'm going to try the version from source, which has it. 
```
pip install git+git://github.com/subhadarship/kmeans_pytorch
```

**Comment by yichen928** [comment]
> 

It should be from the source. Thank you for pointing it out!

**Comment by yichen928** [comment]
It should be from the source. Thank you for pointing it out! You can create new issues if there are any other problems.
