### ISSUE TITLE
 Center_shift became NAN in K-means

### ISSUE THREAD

**Issue by jasper2326** [yichen928/GEAL_active_learning#5]
@yichen928 Hi, I meet a problem while reproducing the result. Center_shift became NAN in K-means.
![image](https://user-images.githubusercontent.com/24251084/156550415-29efd5a2-fbf7-4463-aace-c2d6b4cced8e.png)
How to fix this preblem? Thanks.

**Comment by yichen928** [comment]
Hi, thank you for your interest. This problem should not happen if you set "iter_limit=100" in the kmeans API. You can install the kmeans module following our README from their source code. If you directly install kmeans from pypi, there would be no iter_limit attribution.

**Comment by jasper2326** [comment]
Perfect solution! I built from source code and the problem was solved. Thanks again.

**Comment by abhigoku10** [comment]
@jasper2326 what version of mmdet/ mmcv u r using

**Comment by jasper2326** [comment]
> ###

Well, this issue has nothing to do with the downstream task. You can refer to mmdetection official repo to complete the installation.
